<a href="https://colab.research.google.com/github/rafpank/Colab/blob/main/data_science_bootcamp%20/wprowadzenie/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

#1D array

In [ ]:
x = np.array([1,3,5])
x

array([1, 3, 5])

Kiedy damy print to od razu wyświetla tablicę

In [ ]:
print(x)

[1 3]


In [ ]:
type(x) #wyświetla typ tablicy

numpy.ndarray

In [ ]:
x.ndim #wyświetla wymiar tablicy (w tym wypadku 1)

1

In [ ]:
x.shape #wyświetla kształt tablicy (w tym wypadku 3,) - jeden z najczęściej wykorzystywanych

(3,)

In [ ]:
x.size #wyświetla ilość elementów w tablicy

3

In [ ]:
x.dtype #wyświetla typ danych w tablicy - jeden z najczęściej wykorzystywanych

dtype('int64')

In [ ]:
y = np.array([1.3, 2.3, 1.4])
y

array([1.3, 2.3, 1.4])

In [ ]:
print(y)

[1.3 2.3 1.4]


In [ ]:
y.dtype

dtype('float64')

#2D Array

In [ ]:
x= np.array([[1, 2, 5], [-3, 1, 4]])
x

array([[ 1,  2,  5],
       [-3,  1,  4]])

In [ ]:
print(x)

[[ 1  2  5]
 [-3  1  4]]


In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.shape

(2, 3)

In [ ]:
x.ndim

2

In [ ]:
x.size

6

In [ ]:
type(x)

numpy.ndarray

#3D array - tablice które mogą np. przetrzymywać obraz

In [ ]:
x = np.array(
    [[[4, 3, 1],
     [3, 1, 2]],

      [[ 12, 2, 9],
       [4, 2, 1]]]
    )
x

array([[[ 4,  3,  1],
        [ 3,  1,  2]],

       [[12,  2,  9],
        [ 4,  2,  1]]])

In [ ]:
print(x)

[[[ 4  3  1]
  [ 3  1  2]]

 [[12  2  9]
  [ 4  2  1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

wynik (2, 2, 3) informuje nas że mamy 2 tablice, 2 wiersze i 3 kolumny

#Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A

array([1., 2., 3.])

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.3, 2.7, 3.9], dtype='int')
A

array([1, 2, 3])

Tutaj ważna uwaga, że python w sytuacji gdzy zmienia na int z float64 to za każdym razem zaokrągla w dół np 3.9 -> 3

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

Wbudowane typy danych w bibliotece numPy, mogą być przydatne kiedy chcemy złożyć sobie tablice która ma opisywać zdjęcie i będziemy chcieli przedstawic konkretne wartości pixceli za pomocą tablicy np.array, podając np konkretny typ danych który nie zajmuje az tak dużo miejsca

In [ ]:
A = np.array([24 , 120, 231], dtype=np.int16) #roblem polega na tym, że typ int8 ma ograniczony zakres od -128 do 127, a liczba 231 wykracza poza ten zakres, dlatego uzylem wiekszego zakresu
A.dtype

dtype('int16')

In [ ]:
A = np.array([24 , 120, 231], dtype=np.uint8) #opisuje od 0 do 255
A.dtype

dtype('uint8')

#Tworzenie tablic


In [ ]:
np.zeros(shape=(4, 10)) #możemy też użyć zmiany typu danych np: dtype='int'. Funkcja 'zeros' moze byc przydatna gdy chcemy miec czarny kolr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

żeby zrobić tablice z jednorodnymi cyframi to mozemy użyć funkcji: fill_value= XYZ

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.array(range(9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,100,5) #podaje nam liczby od 10 do 100 z krokiem 5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
np.arange(start=100, stop=10, step=-10) #będzie zmniejszało liczby co 10

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.linspace(start=0, stop=1, num=10) #podaje nam 10 liczb z przedziału od 0 do 1 Elementy te są równo rozłożone

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A= np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1)) #W tej sytuacji, Python automatycznie dobiera liczbę kolumn która będzie pasowała do macierzy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
np.arange(15,30).reshape((-1,5))

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

#Operacje na tablicach


In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
A- B

array([0, 2, 1, 0])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A//B

array([ 1, -1,  1,  1])

In [ ]:
np.floor_divide(A, B)

array([ 1, -1,  1,  1])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

#Mnożenie macierzowe w biliotece NumPy


In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.multiply(X, Y) # to jest zwykłe mnożenie elementów w tych samych miejscach

array([[6, 0],
       [2, 0]])

In [ ]:
(X*Y)

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y) #mnożenie macierzowe czyli wiersz x kolumna [[1*6+3*-1],[1*0+3*2]],[[-2*6+0*-1],[0*6+0*2]]

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y) #jest to to samo mnożenie jak x*y macierzowo

array([[  3,   6],
       [-12,   0]])

mnożenie naprzemienne macierzy nie daje tych samych wyników. To jest jedna z własności macierzy

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y #to samo co dot, czyli standardowe mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

#Generowani liczb pseudolosowych
pseudolosowe, bo one nie do końca mają losowość naturalną

In [ ]:
np.random.seed(0) #za każdym razem ten sam wynik

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10) #10 niby losowo wygenerowanych elementów ze standardowego rozkładu o śreniej 0 i odchyleniu standowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4) #10 wierszy i 4 kolumny

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

Rozkład jednostajny na przedziale 0-1

In [ ]:
np.random.rand()

0.8209932298479351

In [ ]:
np.random.rand(10)

array([0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ,
       0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [ ]:
np.random.rand(10, 2)

array([[0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293]])

In [ ]:
np.random.randint(10) #wygeneruje losową liczbę + całkowit

8

In [ ]:
np.random.randint(low=10, high=101, size=10) #wygeneruje 10 liczb całkowitych z zakresu od 10 do 100

array([ 56, 100,  60,  13,  41,  19,  20,  37,  55,  81])

In [ ]:
np.random.choice([4, 2, 1, 3, 5]) #wybierze losowo jedną wartość z podanej listy

2

In [ ]:
np.random.choice(['python', 'java', 'sql']) #dokonuje też wyboru stringów

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) #wymiesza dane
data

array([7, 2, 3, 8, 0, 6, 9, 1, 5, 4])

In [ ]:
data

array([6, 8, 4, 3, 7, 5, 1, 0, 9, 2])

#Podstawowe funkcje

In [ ]:
np.exp(1) #eksponent stała Eulera

2.718281828459045

In [ ]:
np.exp(4)

54.598150033144236

In [ ]:
np.sqrt(9) #pierwiastek kwadratowy

3.0

In [ ]:
np.all([2,3,1]) #Funkcja logiczna sprawdzająca czy WSZYSTKIE wartości zwracają prawdę czy fałsz

True

In [ ]:
np.any([0,1,0]) #czy którykolwiek element to prawda

True

In [ ]:
np.any([0,0,0])

False

In [ ]:
A = np.random.rand(5) #rozkład jednostajny od 0 do 1 /randn rozkład normalny od -1 do 1
A

array([0.311945  , 0.39822106, 0.20984375, 0.18619301, 0.94437239])

Załóżmy że model wygenerował nam prawdopodobieństwo otrzymania klasy dla danej próbki. Czyli mamy problem klasyfikacji, mamy 5 klas, chcemy którąś klase przyporządkować.
Możemy np. użyć funkcji która wyciagnie nam index przy którym nasza tablica przyjmuje najwyższą wartość

In [ ]:
np.argmax(A) #w tym wypadku zwróciło 4 bo najwyższa wartość jest na ostatnim indexie (0.94437239)

4

Żeby wyciągnąć tą wartość z podanego indexu robimy poniższą funkcję

In [ ]:
A[np.argmax(A)] #wyciąga maksymalną wartość

0.9443723899839336

In [ ]:
np.argmin(A)

3

In [ ]:
np.argsort(A) #sortuje nam indexy od najmniejszej wartości do najwyższej

array([3, 2, 0, 1, 4])

In [ ]:
np.max(A) #zwraca nam wartość maksymalną

0.9443723899839336

In [ ]:
np.min(A)

0.18619300588033616

In [ ]:
np.mean(A) #średnia

0.4101150405070172

In [ ]:
np.median(A) #mediana

0.31194499547960186

In [ ]:
np.std(A) #odchylenie standardowe

0.27765424820577683

#Indeksowanie

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[inx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
np.random.shuffle(A)
A

array([ 1,  8,  6,  0, 17,  2, 11, 16,  3,  4,  7, 10,  9, 13, 14,  5, 19,
       18, 12, 15])

In [ ]:
A[2]

10

In [ ]:
A[:2] # wypisuje wszystkie elementy do elementu na indexie 2

array([9, 0])

In [ ]:
A[3:5] #wypisuje elementy w wybranym zakresie indexów

array([ 4, 18])

In [ ]:
A[3:10:2]

array([3, 5, 7, 9])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 1,  8,  6,  0, 17],
       [ 2, 11, 16,  3,  4],
       [ 7, 10,  9, 13, 14],
       [ 5, 19, 18, 12, 15]])

In [ ]:
A[0] #wyświetla pierwszy wiersz

array([0, 1, 2, 3, 4])

In [ ]:
A[:, 2] # wyświetla 3 kolumnę

array([ 2,  7, 12, 17])

In [ ]:
A[:, -2] #przedostatnia koluna

array([ 0,  3, 13, 12])

Jezeli chcemy wyciąć konkretną liczbę np 7 to podajemy dokładne indexy odzielone przecinkami, gdzie ta liczba się znajduj

In [ ]:
A[2,0] #najpierw który wiersz, a następnie pozycje

7

Natomiast jeżeli chcemy fragment macierzy np 6,7,8 i 11,12,13 podajemy w przedziałach

In [ ]:
A[1:3, 1:4] #należy pamiętać że w przedziale ostatnie liczby nie wchodzą do przedziału

array([[11, 16,  3],
       [10,  9, 13]])

In [ ]:
A[2, 0] = 14 #w ten sposób możemy przypisać liczby na konkretne miejsca. W tym wypadku zastąpiłem 7 na 14
A

array([[ 1,  8,  6,  0, 17],
       [ 2, 11, 16,  3,  4],
       [14, 10,  9, 13, 14],
       [ 5, 19, 18, 12, 15]])

#Iteracja po tablicach

In [ ]:
A

array([[ 1,  8,  6,  0, 17],
       [ 2, 11, 16,  3,  4],
       [14, 10,  9, 13, 14],
       [ 5, 19, 18, 12, 15]])

In [ ]:
for row in A:
  print(row)

[ 1  8  6  0 17]
[ 2 11 16  3  4]
[14 10  9 13 14]
[ 5 19 18 12 15]


In [ ]:
for row in A:
  print(row[1])

8
11
10
19


In [ ]:
for row in A:
  print(row[:3])

[1 8 6]
[ 2 11 16]
[14 10  9]
[ 5 19 18]


Drukowanie po kolei wszsytkich danych z macierzy

In [ ]:
for item in A.flat:
  print(item)

1
8
6
0
17
2
11
16
3
4
14
10
9
13
14
5
19
18
12
15


#Zmiana rozmiaru tablic

In [ ]:
A

array([[ 1,  8,  6,  0, 17],
       [ 2, 11, 16,  3,  4],
       [14, 10,  9, 13, 14],
       [ 5, 19, 18, 12, 15]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5, 4)

array([[ 1,  8,  6,  0],
       [17,  2, 11, 16],
       [ 3,  4, 14, 10],
       [ 9, 13, 14,  5],
       [19, 18, 12, 15]])

In [ ]:
A.ravel() #wypłaszczenie macierzy

array([ 1,  8,  6,  0, 17,  2, 11, 16,  3,  4, 14, 10,  9, 13, 14,  5, 19,
       18, 12, 15])

In [ ]:
A.T #transponowanie macierzy, czyli zamienia kolumny na wiersze

array([[ 1,  2, 14,  5],
       [ 8, 11, 10, 19],
       [ 6, 16,  9, 18],
       [ 0,  3, 13, 12],
       [17,  4, 14, 15]])

#Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1) #-1 oznacza ze ma sie dopasować liczbę kolumn automatycznie
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5, dtype=float)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0 #zwraca nam maskę logiczną na naszą tablicę, z informacją w którym miejscu w nasze tablicy sa wartości ujemne

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A > -5, A < 5) #Ten zapis zwróci nam maskę gdzie oba te warunki są spełnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])