<a href="https://colab.research.google.com/github/rafpank/Colab/blob/main/data_science_bootcamp%20/wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Funkcje statystyczne


In [1]:
import numpy as np

In [2]:
price = np.array([[ 12.4,12.8,11.9,12.6,1000],
[12.5,13.,11.7,12.2, 2000],
[12.2,13.4,12.2,13.2,1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


funkcja sum() - jest to suma wszystkich elementów w tablicy

In [4]:
price.sum()

4650.1

to poniżej działa tak samo

In [7]:
np.sum(price)

4650.1

Jeżeli chcemy policzyc sumę w każdej kolumnie lub wierszu to możemy użyć **axis** tylko trzeba okraślić po której osi mamy liczyć

In [5]:
price.sum(axis=0) #wartość poszczególnych kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [6]:
price.sum(axis=1) #wartość poszczególnych wierszy

array([1049.7, 2049.4, 1551. ])

min()

max()

median()

mean()

In [8]:
np.min(price) #ze wszystkich wartości

11.7

In [9]:
np.min(price,axis=0) #ze wszystkich kolumn

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [10]:
np.min(price,axis=1) #ze wszystkich wierszy

array([11.9, 11.7, 12.2])

Jeżeli byśmy chcieli policzyć srednią zn naszej macierzy, to nie bylibyśmy w stanie tego zrobić bez użycia biblioteki NumPy

In [11]:
np.median(price)

12.6

In [12]:
np.median(price,axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])

In [13]:
np.median(price,axis=1)

array([12.6, 12.5, 13.2])

In [14]:
np.mean(price,axis=0) #liczenie średniej

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [15]:
np.mean(price,axis=1)

array([209.94, 409.88, 310.2 ])

In [16]:
np.mean(price)

310.0066666666667

In [17]:
np.std(price) #odchylenie standardowe

622.3781502877133

In [18]:
np.std(price,axis=0) #odchylenie standardowe poszczególnych kolumn

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [19]:
np.var(price,axis=0) #wariancja poszczególnych kolumn

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [41]:
np.set_printoptions(precision=5, suppress=True) #ustawienie wyświetlania

In [38]:
np.var(price,axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])

In [42]:
np.std(price,axis=0) #odchylenie standardowe poszczególnych kolumn po ustawieniu wyświetlania za pomocą set_printoptions

array([  0.12472,   0.24944,   0.20548,   0.41096, 408.24829])