<a href="https://colab.research.google.com/github/rafpank/Colab/blob/main/data_science_bootcamp%20/uczenie_maszynowe/moje_cwiczenia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
from sklearn.metrics import accuracy_score
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve
import plotly.figure_factory as ff
from sklearn.metrics import classification_report

In [19]:
zer = np.zeros((5), dtype='int')
zer

array([0, 0, 0, 0, 0])

In [16]:
one = np.ones((500), dtype='int')

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.ones((500), dtype='int').reshape(10,50)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [20]:
cobined_array = np.concatenate((zer, one))
cobined_array

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [21]:
one_predict = np.ones(505, dtype='int')
one_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

#Accuracy

In [59]:
accuracy_score(cobined_array, one_predict)

0.9900990099009901

In [60]:
results = pd.DataFrame({'y_true':cobined_array, 'y_pred':one_predict}) #zrobienie DataFrama w celu dalszego przerabiania
results

y_true  y_pred
0         0       1
1         0       1
2         0       1
3         0       1
4         0       1
..      ...     ...
500       1       1
501       1       1
502       1       1
503       1       1
504       1       1

[505 rows x 2 columns]

Tu w sytuacji gdy nie mamy posortowanych danych sortujemy je:
```
results = result.sort_values(by='y_true') #sortowanie po y_true
results = result.reset_index(drop=True) #resetowanie indexu. Gdybym tego nie zrobił to index byłby zgodny z wcześniejszym wyświetleniem
results['sample'] = result.index +1 #tworzymy nową kolumnę z nazwą próbki.
results

```



In [32]:
results['sample'] = results.index +1

Tworzenie obiektu fig

In [34]:
fig = make_subplots(rows=2, cols=1, subplot_titles=('Confusion Matrix', 'ROC Curve'))
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name= 'y_true'), row=1, col=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name= 'y_pred'), row=2, col=1)
fig.update_layout(height=600, width=800, title_text='Confusion Matrix')
fig.show()

Macierz konfuzji (pomyłek)

In [36]:
cm = confusion_matrix(cobined_array, one_predict)
cm

array([[  0,   5],
       [  0, 500]])

In [41]:
def plot_confusion_matrix(cm):
  cm = cm[::-1] #zamieniamy kolejność macierzy konfuzj, bo to jest specyfika tej macierzy
  cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0']) #jako obiekt DataFrame przekazuję obiekty pred i true

  fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                    colorscale='ice', showscale=True, reversescale=True)
  fig.update_layout(width=300, height=300, title='Confusion Matrix', font_size=9)
  fig.show()

plot_confusion_matrix(cm)

In [43]:
cm.ravel()

array([  0,   5,   0, 500])

In [45]:
tn, fp, fn, tp = cm.ravel() #przypisanie nazw

In [46]:
#Błąd pierwszego rodzaju czyli % fałszywie pozytywnych do wszystkich negatywnych
fpr = fp/(fp+tn)
print(f'Błąd pierwszego rodzaju: {fpr}')

Błąd pierwszego rodzaju: 1.0


In [47]:
# Błąd 2 rodzaju - Type II error/ False Negative Rate.
fnr = fn/(fn+tp)
print(f'Błąd drugiego rodzaju: {fnr}')

Błąd drugiego rodzaju: 0.0


In [48]:
precision = tp/(tp+fp)
print(f'Precision, czyli ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne: {precision}')

Precision, czyli ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne: 0.9900990099009901


In [49]:
recall = tp/(tp+fn)
print(f'Recall, czyli ile obserwacji rzeczywicie pozytywnych zostało przewidziane jako pozytywne: {recall}')

Recall, czyli ile obserwacji rzeczywicie pozytywnych zostało przewidziane jako pozytywne: 1.0


In [50]:
f1_score = 2*precision*recall/(precision+recall)
print(f'F1 score: {f1_score}')

F1 score: 0.9950248756218906


In [51]:
minority_precision = tn/(tn+fp)
print(f'Minority Precision: {minority_precision}')

Minority Precision: 0.0


In [54]:
fpr, tpr, thresholds = roc_curve(cobined_array, one_predict) #wylicza false positive rate i true pr, oraz próg za pomocą funkcji roc_curve do której przekazujemy y_true i y_pred. To umożliwia nam wygenerowanie parametrów do wykresu
roc = pd.DataFrame({'fpr': fpr, 'tpr': tpr}) #a ponieważ chcemy stworzyć wykres za pomoca plotlib to tworzymy obiekt DF
roc

fpr  tpr
0  0.0  0.0
1  1.0  1.0

In [61]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1) #pos_label określa klase pozytywna

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=500))
    fig.show()
plot_roc_curve(cobined_array, one_predict)

In [63]:
print(classification_report(cobined_array, one_predict))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.99      1.00      1.00       500

    accuracy                           0.99       505
   macro avg       0.50      0.50      0.50       505
weighted avg       0.98      0.99      0.99       505



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

